Separate detection from action
Network-Tokens/ntf pull request #21
Opened 2020-11-10 19:00 UTC by nevelis

This PR separates the detection of the network token from the action taken on them.  Each packet that belongs to a flow with a network token will have the app ID tagged on each packet (this is a flag that is unconditionally set for now but can be set/cleared by config).  If a DSCP value is specified, a flag is also set to mark the DSCP bits on packets belonging to a flow with a token.

Best to review the commits individually as the first one makes the usage of whitespace consistent.

2020-11-14 05:50 UTC, yiannisy approved these changes

2020-11-14 06:16 UTC, yiannisy requested changes

2020-11-14 06:16 UTC, yiannisy commented on modules/ntf.cc
> +void NTF::MarkPacket(bess::Packet* pkt, const NtfFlowEntry &entry) {
not sure I like the markPacket - a bit vague and metadata is not marking. Can we call it applyActions (or something like this)?

2020-11-14 06:16 UTC, yiannisy commented on modules/ntf.cc
> +void NTF::UnmarkPacket(bess::Packet* pkt) {
Was the original here ResetDscpMarkings? I'd rather keep it explicit instead of mark/unmark.

2020-11-14 06:16 UTC, yiannisy commented on modules/ntf.h
> +     * Unmarks a given packet, removing any NTF metadata and resetting any
Is there a case where we would remove NTF metadata? DSCP bits are reset (when authoritative) because they might be already set and we want to make sure that only valid-tokenized flows can set them.

2020-11-14 06:16 UTC, yiannisy commented on modules/ntf.h
> + * DSCP codepoint.    To prevent abuse, NTF assumes authoritative actions with
Please add here that there are two actions (DSCP and metadata).

2020-11-20 18:49 UTC, nevelis commented on bessctl/conf/ntf.bess
> +  'app_id': 0x10001,
@yiannisy  This is actually a real pain...  We specified in the design doc that we will use the Application ID IE for this purpose.  Now we need to put the token_app_id somewhere else, and we do not have a suitable IE to put it in.

So we either need to stick this in the Custom PFD Contents and include it in a JSON object along with the encryption key, or add an out-of-band mechanism (like we already need to do for the DSCP value) to send it to the NTF-U.

The former approach seems like a hack, and for the latter case, it starts to seem pointless that we are sending down the encryption key via a PFD Management Request at all, since all the other state will be coming across the out-of-band channel (ie: not a PFCP message).

What do you think?

2020-11-20 18:53 UTC, nevelis commented on modules/ntf.cc
> +void NTF::UnmarkPacket(bess::Packet* pkt) {
I guess it's not needed...  MarkPacket does more than just setting the DSCP bits.  UnmarkPacket was supposed to be the inverse action to MarkPacket, but we will never unmark an attribute as we are the ones adding it; we will only ever be clearing the DSCP bits.

2020-11-20 18:56 UTC, nevelis commented on bessctl/conf/ntf.bess
> +  'app_id': 0x10001,
Or perhaps we should stick the entire token configuration (encryption key, app_id, dscp marking) all in the Custom PFD Contents & completely do away with the out of band mechanism?

2020-12-02 18:30 UTC, yiannisy approved these changes

2020-12-02 18:30 UTC, merged