Replaced token handling code with NTF module
Network-Tokens/ntf pull request #23
Opened 2020-12-05 04:34 UTC by nevelis

This is only the header file - nothing actually works, but it compiles,
so we can see what is needed or missing from the API.

2020-12-16 20:38 UTC, yiannisy requested changes

2020-12-16 20:38 UTC, yiannisy commented on CMakeLists.txt
> +set(CMAKE_C_FLAGS "-g3 -ggdb -O0 -march=native -mno-rdseed -W -Wall -Werror")
are the no optimization flags still needed?

2020-12-16 20:38 UTC, yiannisy commented on utils/ntf_api.cc
> +                     token_app_id_t   token_app_id,
I was under the impression that this became "token_type", and within the payload we have a "sid" field. What the final naming convention?

2020-12-16 20:38 UTC, yiannisy commented on utils/ntf_api.h
> + * the packet and no state exists for this flow.
add explanation about field_value and field_length

2020-12-16 20:38 UTC, yiannisy commented on utils/ntf_api.h
> +json_t *
these should be defined as static functions if they are not exposed through the API.

2020-12-16 20:38 UTC, yiannisy commented on utils/ntf_api.h
> + * Bind a field name.  A bound field name is a field name that matches a key in
bind_field name is confusing. 

We use the terms bound_ip, or boud_uid to declare that a token can be used only by this subscriber (which can be identified through its IP address or IMSI). This means that in terms of processing, the token field is verified against a non-token value (like the IP address of the flow that carries the token). 

I think here you want to say something different, which is "give me this value because it will help me decide how I will deal with this packet"

2020-12-16 23:00 UTC, nevelis commented on CMakeLists.txt
> +set(CMAKE_C_FLAGS "-g3 -ggdb -O0 -march=native -mno-rdseed -W -Wall -Werror")
They're fine to be left in.  This build script is only used by the unit tests.  The debugging information/no optimization flags are helpful for debugging unit tests, and the -march=native -mno-rdseed flags are needed for dpdk to work in valgrind.

2020-12-17 18:29 UTC, yiannisy requested changes

2020-12-17 18:29 UTC, yiannisy commented on modules/ntf.cc
> +            set_attr<uint32_t>(this, rule_id_attr, pkt, sid32);
Are we making the assumption here that the sid is the same as the PFD_ID which will be used by the SPGW for FAR/PDR rules?

2020-12-17 18:29 UTC, yiannisy commented on protobuf/ntf_msg.proto
>  	oneof set_dscp {
so you can either set the dscp OR set the metadata, but not both of them?

2020-12-17 18:29 UTC, yiannisy commented on tests/test_nte.cc
>  #include <UnitTest++/UnitTest++.h>
Do we still need this, given nte.cc/h are deleted?

2020-12-17 18:29 UTC, yiannisy commented on utils/ntf_api.h
> + * Identifies which application or service type within a token.
"Identifies the token type which will dictate how to decode a token."

2020-12-17 18:29 UTC, yiannisy commented on utils/ntf_api.h
> +typedef uint8_t dscp_t;
Not clear what a "type" with regards to DSCP.

2020-12-17 18:29 UTC, yiannisy commented on utils/ntf_api.h
> + * \param key Pointer to encryption key (JWT)
JWT -> JWK

2020-12-17 18:29 UTC, yiannisy commented on utils/ntf_api.h
> + * \param dscp If >0, indicate the DSCP value to set on packets of flows that
that have a valid token.

2020-12-17 18:29 UTC, yiannisy commented on utils/ntf_api.h
> +ntf_context_token_type_add( ntf_context_t * ctx,
would this read better if we call it ntf_context_entry_add ?

2020-12-17 18:29 UTC, yiannisy commented on utils/ntf_api.h
> +ntf_context_whitelist_count( const ntf_context_t * ctx );
Embrace the change and rename this to allowlist. I've been corrected twice already for using the term "whitelist".

2020-12-18 00:05 UTC, nevelis commented on protobuf/ntf_msg.proto
>  	oneof set_dscp {
No... this is just how you express an optional field in protobuf - by using "oneof" with one option.

2020-12-18 00:05 UTC, nevelis commented on tests/test_nte.cc
>  #include <UnitTest++/UnitTest++.h>
This probably should be renamed to test_ntf_decrypt

2020-12-18 00:20 UTC, nevelis commented on modules/ntf.cc
> +            set_attr<uint32_t>(this, rule_id_attr, pkt, sid32);
Hmmmmmmmm.... I think this is wrong because they are in different namespaces.  I'm not sure I reached this bit of code yet to change it.  Let me come back to this.

2020-12-18 00:31 UTC, nevelis commented on utils/ntf_api.h
> +typedef uint8_t dscp_t;
I guess all DSCPs are 8 bits, so we can remove it

2020-12-18 00:32 UTC, nevelis commented on utils/ntf_api.h
> +ntf_context_token_type_add( ntf_context_t * ctx,
Definitely

2020-12-18 00:46 UTC, nevelis commented on utils/ntf_api.h
> +ntf_context_whitelist_count( const ntf_context_t * ctx );
Change has been embraced.

2020-12-18 01:06 UTC, nevelis commented on modules/ntf.cc
> +            set_attr<uint32_t>(this, rule_id_attr, pkt, sid32);
@yiannisy We are making this assumption for now, but we'll come back to this.  I think it'll make more sense after we flesh out how an operator would configure/deploy this, so I'll leave it in there like that for now if that's okay.

2020-12-18 05:03 UTC, yiannisy approved these changes

2020-12-18 05:03 UTC, merged